package db

var IdTypes = [7]string{
	"RUC ",
	"CEDULA ",
	"PASAPORTE ",
	"CARNE DE MIGRACION ",
	"NÚMERO DE EMPLEADOR ",
	"IDENTIFICACIÓN TRIBUTARIA (PROVEEDORES DEL EXTERIOR) ",
}

var IncomeDocTypes = []string{
	"FACTURA ",
	"BOLETA DE VENTA ",
	"TICKET DE MÁQUINA REGISTRADORA ",
	"ENTRADA A ESPECTÁCULOS PÚBLICOS ",
	"BOLETO DE TRANSPORTE PÚBLICO ",
	"TICKET DE TRANSPORTE AÉREO ",
	"BOLETO DE LOTERÍA, APUESTAS Y DEMÁS JUEGOS DE AZAR ",
	"NOTA DE DÉBITO EMITIDA ",
	"NOTA DE CRÉDITO RECIBIDA ",
	"LIQUIDACIÓN DE SALARIO ",
	"EXTRACTO DE CUENTA (Cuando no exista la obligación legal de expedir comprobante de venta) ",
	"OTROS DOCUMENTOS QUE RESPALDAN LOS INGRESOS (Cuando no exista la obligación legal de expedir comprobante de venta) ",
	"COMPROBANTE DE INGRESO ",
	"OTROS ",
}

var ExpenseDocTypes = []string{
	"FACTURA ",
	"BOLETA DE VENTA ",
	"AUTOFACTURA ",
	"BOLETA RESIMPLE ",
	"TICKET DE MÁQUINA REGISTRADORA ",
	"ENTRADA A ESPECTÁCULOS PÚBLICOS ",
	"BOLETO DE TRANSPORTE PÚBLICO ",
	"TICKET DE TRANSPORTE AÉREO ",
	"NOTA DE DÉBITO RECIBIDA ",
	"NOTA DE CRÉDITO EMITIDA ",
	"LIQUIDACIÓN DE SALARIO ",
	"EXTRACTO DE CUENTA IPS ",
	"EXTRACTO DE TARJETA DE CRÉDITO/TARJETA DE DÉBITO ",
	"TRANSFERENCIAS O GIROS BANCARIOS/ BOLETA DE DEPÓSITO ",
	"COMPROBANTE DEL EXTERIOR LEGALIZADO ",
	"COMPROBANTE DE INGRESO O RECIBO DE ENTIDAD PÚBLICA, RELIGIOSAS O DE BENEFICIO PÚBLICO ",
	"DESPACHO DE IMPORTACIÓN ",
	"OTROS COMPROBANTES DE VENTA QUE RESPALDEN EGRESOS (Cuando no exista obligación legal de expedir comprobantes de ventas) ",
}
